baseurl = "http://localhost/"
languageCode = "en-us"
title = "Nick Feller"
theme = "academic"

[params]
  name = "Nick Feller"
  role = "Artificial Intelligence Research At Concordia University And Software Engineer at Ericsson"
  avatar = "nick.jpg"
  email = "me@nicolasfeller.com"
  address = "3959 rue Clark, Montreal, Quebec, Canada - H2W 1W8"
  phone = "(514) 984-6425"

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering? If false, you can enable it locally on a per page basis.
  math = false

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Biography section.
  # Section will only be displayed if `content/home/about.md` exists.
  [params.about]
    interests = ["Artificial Intelligence", "Software Development", "Philosophy", "Hicking - Camping", "Litterature"]
    str_interests = "Interests"
    str_education = "Education"

    [[params.about.education]]
      course = "B.Eng Computer Engineering"
      institution = "Concordia University"
      year = 2017

    [[params.about.education]]
      course = "B.Comm Finance"
      institution = "John Molson School of Business"
      year = 2012

  # Selected Publications section.
  # Section will only be displayed if there are publications with `selected = true` in their `+++` preamble.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 10
    detailed_list = false
    title = "Recent Publications"
    subtitle = ""
    str_all = "More Publications"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 5
    title = "Recent Posts"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = ""

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = true  # Automatically link email and phone?

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus, youtube, instagram, soundcloud
  #   For email icon, use "fa" icon pack, "envelope" icon, and "mailto:your@email.com" as the link.
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:me@nicolasfeller.com"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/NickyFellz"

  [[params.social]]
    icon = "facebook"
    icon_pack = "fa"
    link = "https://www.facebook.com/nicky.feller"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "https://github.com/nrkfeller"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "https://ca.linkedin.com/in/nicolasfeller"

# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#top"
  weight = 1

[[menu.main]]
  name = "Work Experience"
  url = "#experience"
  weight = 2

[[menu.main]]
  name = "Booklist"
  url = "#booklist"
  weight = 3


[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4
